#:kivy 1.0.9

<PiCV_Widget>:
    canvas:
        Rectangle:
            pos: self.center_x-5, 0
            size: 10, self.height

    Label:
        font_size: 70
        center_x: root.width / 4
        top: root.top - 50
        text: str("root.player1.score")

    Label:
        font_size: 70
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: str("root.player2.score")
